### PR TITLE
Add xylar as a maintainer

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge/python3-openid, I'd like to merge #16 and am happy to take care of it if you would like another maintainer.

**Comment by xylar** [comment]
I'm not bumping the build number because we don't need a new build just to add me as a maintainer.

**Comment by xylar** [comment]
@conda-forge-admin, please restart ci

**Comment by carlodri** [comment]
Thanks for volunteering @xylar! I'm adding you as maintainer in #16

**Pull request closed without merging**
